-- 01: Структура. Запускайте перед 02–05.
create extension if not exists pgcrypto;
create sequence if not exists public.application_number_seq;
create sequence if not exists public.appeal_number_seq;
create table if not exists public.departments (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text unique not null, description text default '', email text, phone text, active boolean default true);
create table if not exists public.profiles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid unique not null references auth.users(id) on delete cascade, email text, first_name text default '', last_name text default '', middle_name text default '', phone text, birth_date date, avatar_path text, blocked boolean not null default false);
create table if not exists public.roles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text unique not null check(name in ('super_admin','admin','department_admin','operator','editor','appeals_operator','viewer')), label text not null);
create table if not exists public.user_roles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id) on delete cascade, role_name text not null references roles(name), unique(user_id,role_name));
create table if not exists public.staff_departments (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id) on delete cascade, department_id uuid not null references departments(id) on delete cascade, unique(user_id,department_id));
create table if not exists public.service_categories (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text unique not null, description text default '', icon text default 'Building2', sort_order int default 0);
create table if not exists public.appeal_categories (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text unique not null, description text default '', department_id uuid references departments(id));
create table if not exists public.news_categories (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text unique not null, description text default '');
create table if not exists public.document_categories (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text unique not null, description text default '');
create table if not exists public.services (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text unique not null, summary text default '', content text default '', category_id uuid references service_categories(id), department_id uuid references departments(id), format text not null default 'online' check(format in ('online','offline','hybrid')), audience text[] default array['residents'], duration text default '', cost text default 'Безкоштовно', eligibility text default '', requirements text default '', steps text default '', result text default '', legal_basis text default '', contacts text default '', faq jsonb default '[]', available boolean default true, featured boolean default false, status text not null default 'draft' check(status in ('draft','published','scheduled','archived')), published_at timestamptz default now(), deleted_at timestamptz, is_demo boolean default false);
create table if not exists public.service_forms (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), service_id uuid not null unique references services(id) on delete cascade, title text not null default 'Заява', version int not null default 1, active boolean default true);
create table if not exists public.service_form_fields (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), form_id uuid not null references service_forms(id) on delete cascade, key text not null check(key ~ '^[a-zA-Z][a-zA-Z0-9_]*$'), type text not null check(type in ('text','textarea','email','phone','number','date','select','multiselect','radio','checkbox','address','file','image','pdf','confirmation','heading','information')), label text not null, placeholder text default '', required boolean default false, help_text text default '', validation jsonb default '{}', options jsonb default '[]', sort_order int default 0, unique(form_id,key));
create table if not exists public.applications (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id), service_id uuid not null references services(id), department_id uuid references departments(id), number text unique, status text not null default 'draft' check(status in ('draft','submitted','received','in_review','needs_more_info','approved','rejected','completed','cancelled')), assignee_id uuid references auth.users(id), data jsonb not null default '{}', form_snapshot jsonb not null default '[]', submitted_at timestamptz, deleted_at timestamptz);
create table if not exists public.application_answers (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), application_id uuid not null references applications(id) on delete cascade, field_key text not null, value jsonb, unique(application_id,field_key));
create table if not exists public.application_files (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), application_id uuid not null references applications(id) on delete cascade, user_id uuid not null references auth.users(id), field_key text, name text not null, path text not null unique, mime_type text, size_bytes bigint check(size_bytes between 0 and 10485760));
create table if not exists public.application_status_history (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), application_id uuid not null references applications(id) on delete cascade, actor_id uuid references auth.users(id), old_status text, new_status text not null, note text default '');
create table if not exists public.application_messages (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), application_id uuid not null references applications(id) on delete cascade, user_id uuid not null references auth.users(id), message text not null check(length(message) between 1 and 10000), internal boolean not null default false);
create table if not exists public.appeals (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id), category_id uuid references appeal_categories(id), department_id uuid references departments(id), number text unique, title text not null, location text default '', message text not null, status text not null default 'new' check(status in ('new','received','forwarded','in_progress','completed','rejected')), assignee_id uuid references auth.users(id), response text default '', deleted_at timestamptz);
create table if not exists public.appeal_files (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), appeal_id uuid not null references appeals(id) on delete cascade, user_id uuid not null references auth.users(id), name text not null, path text unique not null, mime_type text, size_bytes bigint check(size_bytes between 0 and 10485760));
create table if not exists public.appeal_status_history (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), appeal_id uuid not null references appeals(id) on delete cascade, actor_id uuid references auth.users(id), old_status text, new_status text not null, note text default '');
create table if not exists public.news (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text unique not null, summary text default '', content text default '', category_id uuid references news_categories(id), cover_path text, gallery jsonb default '[]', author text default '', featured boolean default false, status text not null default 'draft' check(status in ('draft','published','scheduled','archived')), published_at timestamptz default now(), deleted_at timestamptz, is_demo boolean default false);
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), type text default 'info', title text not null, message text not null, start_at timestamptz default now(), end_at timestamptz, priority int default 0, dismissible boolean default true, placement text default 'banner' check(placement in ('banner','modal','pinned')), button_text text, button_url text, active boolean default true);
create table if not exists public.documents (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text unique not null, document_number text, date date, category_id uuid references document_categories(id), description text default '', file_path text, filename text, tags text[] default '{}', status text not null default 'draft' check(status in ('draft','published','scheduled','archived')), published_at timestamptz default now(), deleted_at timestamptz, is_demo boolean default false);
create table if not exists public.events (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text unique not null, summary text default '', content text default '', starts_at timestamptz, location text default '', cover_path text, category text default '', organizer text default '', registration_url text, status text not null default 'draft' check(status in ('draft','published','scheduled','archived')), published_at timestamptz default now(), deleted_at timestamptz, is_demo boolean default false);
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id) on delete cascade, type text not null default 'system' check(type in ('system','application','service','emergency','news')), title text not null, message text default '', link text, read_at timestamptz);
create table if not exists public.saved_services (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id) on delete cascade, service_id uuid not null references services(id) on delete cascade, unique(user_id,service_id));
create table if not exists public.user_addresses (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, city text default 'Черкаси', street text not null, building text not null, apartment text, note text);
create table if not exists public.user_documents (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, path text not null unique, mime_type text, size_bytes bigint check(size_bytes between 0 and 10485760));
create table if not exists public.faqs (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), question text not null, answer text not null, category text default 'Загальне', sort_order int default 0, published boolean default true, is_demo boolean default false);
create table if not exists public.site_settings (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), key text not null unique, value jsonb not null);
create table if not exists public.city_status (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), type text not null, title text not null, status text default '', severity text default 'info' check(severity in ('normal','info','warning','danger','critical')), description text default '', started_at timestamptz default now(), ended_at timestamptz, is_active boolean default true, source_label text default 'Введено диспетчером');
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), actor_id uuid references auth.users(id), action text not null, entity text not null, entity_id uuid, metadata jsonb default '{}');
create table if not exists public.account_deletion_requests (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id), status text not null default 'pending' check(status in ('pending','processing','completed','rejected')), note text default '');
create table if not exists public.api_cache (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), key text unique not null, payload jsonb not null default '{}', refreshed_at timestamptz, lease_until timestamptz, last_error text);
create index if not exists departments_created_idx on public.departments(created_at);
create index if not exists profiles_created_idx on public.profiles(created_at);
create index if not exists roles_created_idx on public.roles(created_at);
create index if not exists user_roles_created_idx on public.user_roles(created_at);
create index if not exists user_roles_user_id_idx on public.user_roles(user_id);
create index if not exists staff_departments_created_idx on public.staff_departments(created_at);
create index if not exists staff_departments_user_id_idx on public.staff_departments(user_id);
create index if not exists staff_departments_department_id_idx on public.staff_departments(department_id);
create index if not exists service_categories_created_idx on public.service_categories(created_at);
create index if not exists appeal_categories_created_idx on public.appeal_categories(created_at);
create index if not exists appeal_categories_department_id_idx on public.appeal_categories(department_id);
create index if not exists news_categories_created_idx on public.news_categories(created_at);
create index if not exists document_categories_created_idx on public.document_categories(created_at);
create index if not exists services_created_idx on public.services(created_at);
create index if not exists services_category_id_idx on public.services(category_id);
create index if not exists services_department_id_idx on public.services(department_id);
create index if not exists services_status_idx on public.services(status);
create index if not exists services_category_id_idx on public.services(category_id);
create index if not exists services_published_at_idx on public.services(published_at);
create index if not exists service_forms_created_idx on public.service_forms(created_at);
create index if not exists service_form_fields_created_idx on public.service_form_fields(created_at);
create index if not exists service_form_fields_form_id_idx on public.service_form_fields(form_id);
create index if not exists applications_created_idx on public.applications(created_at);
create index if not exists applications_user_id_idx on public.applications(user_id);
create index if not exists applications_service_id_idx on public.applications(service_id);
create index if not exists applications_department_id_idx on public.applications(department_id);
create index if not exists applications_assignee_id_idx on public.applications(assignee_id);
create index if not exists applications_status_idx on public.applications(status);
create index if not exists application_answers_created_idx on public.application_answers(created_at);
create index if not exists application_answers_application_id_idx on public.application_answers(application_id);
create index if not exists application_files_created_idx on public.application_files(created_at);
create index if not exists application_files_application_id_idx on public.application_files(application_id);
create index if not exists application_files_user_id_idx on public.application_files(user_id);
create index if not exists application_status_history_created_idx on public.application_status_history(created_at);
create index if not exists application_status_history_application_id_idx on public.application_status_history(application_id);
create index if not exists application_status_history_actor_id_idx on public.application_status_history(actor_id);
create index if not exists application_messages_created_idx on public.application_messages(created_at);
create index if not exists application_messages_application_id_idx on public.application_messages(application_id);
create index if not exists application_messages_user_id_idx on public.application_messages(user_id);
create index if not exists appeals_created_idx on public.appeals(created_at);
create index if not exists appeals_user_id_idx on public.appeals(user_id);
create index if not exists appeals_category_id_idx on public.appeals(category_id);
create index if not exists appeals_department_id_idx on public.appeals(department_id);
create index if not exists appeals_assignee_id_idx on public.appeals(assignee_id);
create index if not exists appeals_status_idx on public.appeals(status);
create index if not exists appeals_category_id_idx on public.appeals(category_id);
create index if not exists appeal_files_created_idx on public.appeal_files(created_at);
create index if not exists appeal_files_appeal_id_idx on public.appeal_files(appeal_id);
create index if not exists appeal_files_user_id_idx on public.appeal_files(user_id);
create index if not exists appeal_status_history_created_idx on public.appeal_status_history(created_at);
create index if not exists appeal_status_history_appeal_id_idx on public.appeal_status_history(appeal_id);
create index if not exists appeal_status_history_actor_id_idx on public.appeal_status_history(actor_id);
create index if not exists news_created_idx on public.news(created_at);
create index if not exists news_category_id_idx on public.news(category_id);
create index if not exists news_status_idx on public.news(status);
create index if not exists news_category_id_idx on public.news(category_id);
create index if not exists news_published_at_idx on public.news(published_at);
create index if not exists announcements_created_idx on public.announcements(created_at);
create index if not exists documents_created_idx on public.documents(created_at);
create index if not exists documents_category_id_idx on public.documents(category_id);
create index if not exists documents_status_idx on public.documents(status);
create index if not exists documents_category_id_idx on public.documents(category_id);
create index if not exists documents_published_at_idx on public.documents(published_at);
create index if not exists events_created_idx on public.events(created_at);
create index if not exists events_status_idx on public.events(status);
create index if not exists events_published_at_idx on public.events(published_at);
create index if not exists notifications_created_idx on public.notifications(created_at);
create index if not exists notifications_user_id_idx on public.notifications(user_id);
create index if not exists saved_services_created_idx on public.saved_services(created_at);
create index if not exists saved_services_user_id_idx on public.saved_services(user_id);
create index if not exists saved_services_service_id_idx on public.saved_services(service_id);
create index if not exists user_addresses_created_idx on public.user_addresses(created_at);
create index if not exists user_addresses_user_id_idx on public.user_addresses(user_id);
create index if not exists user_documents_created_idx on public.user_documents(created_at);
create index if not exists user_documents_user_id_idx on public.user_documents(user_id);
create index if not exists faqs_created_idx on public.faqs(created_at);
create index if not exists site_settings_created_idx on public.site_settings(created_at);
create index if not exists city_status_created_idx on public.city_status(created_at);
create index if not exists city_status_status_idx on public.city_status(status);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at);
create index if not exists audit_logs_actor_id_idx on public.audit_logs(actor_id);
create index if not exists account_deletion_requests_created_idx on public.account_deletion_requests(created_at);
create index if not exists account_deletion_requests_user_id_idx on public.account_deletion_requests(user_id);
create index if not exists account_deletion_requests_status_idx on public.account_deletion_requests(status);
create index if not exists api_cache_created_idx on public.api_cache(created_at);
