-- 03: Row Level Security. No private table has anonymous reads.
alter table public.departments enable row level security;
grant select,insert,update,delete on public.departments to authenticated;
grant select on public.departments to anon;
alter table public.profiles enable row level security;
grant select,insert,update,delete on public.profiles to authenticated;
grant select on public.profiles to anon;
alter table public.roles enable row level security;
grant select,insert,update,delete on public.roles to authenticated;
grant select on public.roles to anon;
alter table public.user_roles enable row level security;
grant select,insert,update,delete on public.user_roles to authenticated;
grant select on public.user_roles to anon;
alter table public.staff_departments enable row level security;
grant select,insert,update,delete on public.staff_departments to authenticated;
grant select on public.staff_departments to anon;
alter table public.service_categories enable row level security;
grant select,insert,update,delete on public.service_categories to authenticated;
grant select on public.service_categories to anon;
alter table public.appeal_categories enable row level security;
grant select,insert,update,delete on public.appeal_categories to authenticated;
grant select on public.appeal_categories to anon;
alter table public.news_categories enable row level security;
grant select,insert,update,delete on public.news_categories to authenticated;
grant select on public.news_categories to anon;
alter table public.document_categories enable row level security;
grant select,insert,update,delete on public.document_categories to authenticated;
grant select on public.document_categories to anon;
alter table public.services enable row level security;
grant select,insert,update,delete on public.services to authenticated;
grant select on public.services to anon;
alter table public.service_forms enable row level security;
grant select,insert,update,delete on public.service_forms to authenticated;
grant select on public.service_forms to anon;
alter table public.service_form_fields enable row level security;
grant select,insert,update,delete on public.service_form_fields to authenticated;
grant select on public.service_form_fields to anon;
alter table public.applications enable row level security;
grant select,insert,update,delete on public.applications to authenticated;
grant select on public.applications to anon;
alter table public.application_answers enable row level security;
grant select,insert,update,delete on public.application_answers to authenticated;
grant select on public.application_answers to anon;
alter table public.application_files enable row level security;
grant select,insert,update,delete on public.application_files to authenticated;
grant select on public.application_files to anon;
alter table public.application_status_history enable row level security;
grant select,insert,update,delete on public.application_status_history to authenticated;
grant select on public.application_status_history to anon;
alter table public.application_messages enable row level security;
grant select,insert,update,delete on public.application_messages to authenticated;
grant select on public.application_messages to anon;
alter table public.appeals enable row level security;
grant select,insert,update,delete on public.appeals to authenticated;
grant select on public.appeals to anon;
alter table public.appeal_files enable row level security;
grant select,insert,update,delete on public.appeal_files to authenticated;
grant select on public.appeal_files to anon;
alter table public.appeal_status_history enable row level security;
grant select,insert,update,delete on public.appeal_status_history to authenticated;
grant select on public.appeal_status_history to anon;
alter table public.news enable row level security;
grant select,insert,update,delete on public.news to authenticated;
grant select on public.news to anon;
alter table public.announcements enable row level security;
grant select,insert,update,delete on public.announcements to authenticated;
grant select on public.announcements to anon;
alter table public.documents enable row level security;
grant select,insert,update,delete on public.documents to authenticated;
grant select on public.documents to anon;
alter table public.events enable row level security;
grant select,insert,update,delete on public.events to authenticated;
grant select on public.events to anon;
alter table public.notifications enable row level security;
grant select,insert,update,delete on public.notifications to authenticated;
grant select on public.notifications to anon;
alter table public.saved_services enable row level security;
grant select,insert,update,delete on public.saved_services to authenticated;
grant select on public.saved_services to anon;
alter table public.user_addresses enable row level security;
grant select,insert,update,delete on public.user_addresses to authenticated;
grant select on public.user_addresses to anon;
alter table public.user_documents enable row level security;
grant select,insert,update,delete on public.user_documents to authenticated;
grant select on public.user_documents to anon;
alter table public.faqs enable row level security;
grant select,insert,update,delete on public.faqs to authenticated;
grant select on public.faqs to anon;
alter table public.site_settings enable row level security;
grant select,insert,update,delete on public.site_settings to authenticated;
grant select on public.site_settings to anon;
alter table public.city_status enable row level security;
grant select,insert,update,delete on public.city_status to authenticated;
grant select on public.city_status to anon;
alter table public.audit_logs enable row level security;
grant select,insert,update,delete on public.audit_logs to authenticated;
grant select on public.audit_logs to anon;
alter table public.account_deletion_requests enable row level security;
grant select,insert,update,delete on public.account_deletion_requests to authenticated;
grant select on public.account_deletion_requests to anon;
alter table public.api_cache enable row level security;
grant select,insert,update,delete on public.api_cache to authenticated;
grant select on public.api_cache to anon;
grant usage on schema public to anon,authenticated;
drop policy if exists public_read on public.service_categories;
create policy public_read on public.service_categories for select to anon,authenticated using (true);
drop policy if exists admin_write on public.service_categories;
create policy admin_write on public.service_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists public_read on public.news_categories;
create policy public_read on public.news_categories for select to anon,authenticated using (true);
drop policy if exists admin_write on public.news_categories;
create policy admin_write on public.news_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists public_read on public.document_categories;
create policy public_read on public.document_categories for select to anon,authenticated using (true);
drop policy if exists admin_write on public.document_categories;
create policy admin_write on public.document_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists public_read on public.appeal_categories;
create policy public_read on public.appeal_categories for select to anon,authenticated using (true);
drop policy if exists admin_write on public.appeal_categories;
create policy admin_write on public.appeal_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists public_read on public.departments;
create policy public_read on public.departments for select to anon,authenticated using (true);
drop policy if exists admin_write on public.departments;
create policy admin_write on public.departments for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read on public.news;
create policy read on public.news for select to anon,authenticated using (public.content_visible(status,published_at,deleted_at) or public.has_role(array['super_admin','admin','editor']));
drop policy if exists edit on public.news;
create policy edit on public.news for all to authenticated using (public.has_role(array['super_admin','admin','editor'])) with check (public.has_role(array['super_admin','admin','editor']));
drop policy if exists read on public.documents;
create policy read on public.documents for select to anon,authenticated using (public.content_visible(status,published_at,deleted_at) or public.has_role(array['super_admin','admin','editor']));
drop policy if exists edit on public.documents;
create policy edit on public.documents for all to authenticated using (public.has_role(array['super_admin','admin','editor'])) with check (public.has_role(array['super_admin','admin','editor']));
drop policy if exists read on public.events;
create policy read on public.events for select to anon,authenticated using (public.content_visible(status,published_at,deleted_at) or public.has_role(array['super_admin','admin','editor']));
drop policy if exists edit on public.events;
create policy edit on public.events for all to authenticated using (public.has_role(array['super_admin','admin','editor'])) with check (public.has_role(array['super_admin','admin','editor']));
drop policy if exists read on public.services;
create policy read on public.services for select to anon,authenticated using (public.content_visible(status,published_at,deleted_at) or public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(department_id)) or (public.is_active_user() and exists(select 1 from applications a where a.service_id=services.id and public.app_access(a.id))));
drop policy if exists edit on public.services;
create policy edit on public.services for all to authenticated using (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(department_id))) with check (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(department_id)));
drop policy if exists read on public.service_forms;
create policy read on public.service_forms for select to anon,authenticated using (exists(select 1 from services s where s.id=service_id and (public.content_visible(s.status,s.published_at,s.deleted_at) or (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(s.department_id))))));
drop policy if exists edit on public.service_forms;
create policy edit on public.service_forms for all to authenticated using (exists(select 1 from services s where s.id=service_id and (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(s.department_id))))) with check (exists(select 1 from services s where s.id=service_id and (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(s.department_id)))));
drop policy if exists read on public.service_form_fields;
create policy read on public.service_form_fields for select to anon,authenticated using (exists(select 1 from service_forms f join services s on s.id=f.service_id where f.id=form_id and (public.content_visible(s.status,s.published_at,s.deleted_at) or (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(s.department_id))))));
drop policy if exists edit on public.service_form_fields;
create policy edit on public.service_form_fields for all to authenticated using (exists(select 1 from service_forms f join services s on s.id=f.service_id where f.id=form_id and (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(s.department_id))))) with check (exists(select 1 from service_forms f join services s on s.id=f.service_id where f.id=form_id and (public.is_admin() or (public.has_role(array['department_admin']) and public.in_department(s.department_id)))));
drop policy if exists read on public.profiles;
create policy read on public.profiles for select to authenticated using (public.is_active_user() and (user_id=auth.uid() or public.is_admin() or exists(select 1 from applications a where a.user_id=profiles.user_id and public.can_app(a.department_id)) or exists(select 1 from appeals a where a.user_id=profiles.user_id and public.can_appeal(a.department_id)) or exists(select 1 from staff_departments sd where sd.user_id=profiles.user_id and public.in_department(sd.department_id))));
drop policy if exists owner_update on public.profiles;
create policy owner_update on public.profiles for update to authenticated using (public.is_active_user() and user_id=auth.uid()) with check (public.is_active_user() and user_id=auth.uid());
drop policy if exists read on public.roles;
create policy read on public.roles for select to authenticated using (public.is_active_user());
drop policy if exists read on public.user_roles;
create policy read on public.user_roles for select to authenticated using (public.is_active_user() and (user_id=auth.uid() or public.is_admin()));
drop policy if exists read on public.staff_departments;
create policy read on public.staff_departments for select to authenticated using (public.is_active_user() and (user_id=auth.uid() or public.is_admin() or public.in_department(department_id)));
drop policy if exists owner on public.saved_services;
create policy owner on public.saved_services for all to authenticated using (public.is_active_user() and user_id=auth.uid()) with check (public.is_active_user() and user_id=auth.uid());
drop policy if exists owner on public.user_addresses;
create policy owner on public.user_addresses for all to authenticated using (public.is_active_user() and user_id=auth.uid()) with check (public.is_active_user() and user_id=auth.uid());
drop policy if exists owner on public.user_documents;
create policy owner on public.user_documents for all to authenticated using (public.is_active_user() and user_id=auth.uid()) with check (public.is_active_user() and user_id=auth.uid());
drop policy if exists read on public.applications;
create policy read on public.applications for select to authenticated using (public.is_active_user() and (user_id=auth.uid() or public.can_app(department_id)));
drop policy if exists read on public.appeals;
create policy read on public.appeals for select to authenticated using (public.is_active_user() and (user_id=auth.uid() or public.can_appeal(department_id)));
drop policy if exists read on public.application_answers;
create policy read on public.application_answers for select to authenticated using (public.app_access(application_id));
drop policy if exists read on public.application_status_history;
create policy read on public.application_status_history for select to authenticated using (public.app_access(application_id));
drop policy if exists read on public.application_files;
create policy read on public.application_files for select to authenticated using (public.app_access(application_id));
drop policy if exists read on public.application_messages;
create policy read on public.application_messages for select to authenticated using (public.app_access(application_id) and (not internal or exists(select 1 from applications a where a.id=application_id and public.can_app(a.department_id))));
drop policy if exists insert on public.application_messages;
create policy insert on public.application_messages for insert to authenticated with check (public.is_active_user() and user_id=auth.uid() and exists(select 1 from applications a where a.id=application_id and a.status<>'draft' and ((a.user_id=auth.uid() and not internal) or public.can_app(a.department_id,true))));
drop policy if exists insert on public.application_files;
create policy insert on public.application_files for insert to authenticated with check (public.is_active_user() and user_id=auth.uid() and exists(select 1 from applications a where a.id=application_id and ((a.user_id=auth.uid() and a.status in ('draft','needs_more_info')) or public.can_app(a.department_id,true))));
drop policy if exists delete on public.application_files;
create policy delete on public.application_files for delete to authenticated using (public.is_active_user() and user_id=auth.uid() and exists(select 1 from applications a where a.id=application_id and a.user_id=auth.uid() and a.status in ('draft','needs_more_info')));
drop policy if exists read on public.appeal_files;
create policy read on public.appeal_files for select to authenticated using (public.appeal_access(appeal_id));
drop policy if exists read on public.appeal_status_history;
create policy read on public.appeal_status_history for select to authenticated using (public.appeal_access(appeal_id));
drop policy if exists insert on public.appeal_files;
create policy insert on public.appeal_files for insert to authenticated with check (public.is_active_user() and user_id=auth.uid() and exists(select 1 from appeals a where a.id=appeal_id and a.user_id=auth.uid() and a.status='new'));
drop policy if exists read on public.notifications;
create policy read on public.notifications for select to authenticated using (public.is_active_user() and user_id=auth.uid());
drop policy if exists read on public.faqs;
create policy read on public.faqs for select to anon,authenticated using ((published) or public.is_admin());
drop policy if exists admin_write on public.faqs;
create policy admin_write on public.faqs for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read on public.site_settings;
create policy read on public.site_settings for select to anon,authenticated using ((true) or public.is_admin());
drop policy if exists admin_write on public.site_settings;
create policy admin_write on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read on public.announcements;
create policy read on public.announcements for select to anon,authenticated using ((active and start_at<=now() and (end_at is null or end_at>now())) or public.is_admin());
drop policy if exists admin_write on public.announcements;
create policy admin_write on public.announcements for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read on public.city_status;
create policy read on public.city_status for select to anon,authenticated using ((is_active and (ended_at is null or ended_at>now())) or public.is_admin());
drop policy if exists admin_write on public.city_status;
create policy admin_write on public.city_status for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read on public.audit_logs;
create policy read on public.audit_logs for select to authenticated using (public.is_admin());
drop policy if exists read on public.account_deletion_requests;
create policy read on public.account_deletion_requests for select to authenticated using (public.is_active_user() and (user_id=auth.uid() or public.is_admin()));
drop policy if exists insert on public.account_deletion_requests;
create policy insert on public.account_deletion_requests for insert to authenticated with check (public.is_active_user() and user_id=auth.uid() and status='pending');
drop policy if exists admin_update on public.account_deletion_requests;
create policy admin_update on public.account_deletion_requests for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read on public.api_cache;
create policy read on public.api_cache for select to anon,authenticated using (key='alerts');

-- Metadata cannot point to a different user's object or another parent.
create or replace function public.guard_file_metadata() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
 declare bucket text; expected text;begin
 if TG_TABLE_NAME='application_files' then bucket='application-files';expected=new.user_id::text||'/'||new.application_id::text||'/';
 elsif TG_TABLE_NAME='appeal_files' then bucket='appeal-files';expected=new.user_id::text||'/'||new.appeal_id::text||'/';
 else bucket='service-documents';expected='personal/'||new.user_id::text||'/';end if;
 if left(new.path,length(expected))<>expected or not exists(select 1 from storage.objects where bucket_id=bucket and name=new.path) then raise exception 'Некоректний файл';end if;
 return new;end;$$;
