import {useEffect,useRef,useState} from "react";
import {Link,useLocation,useNavigate} from "react-router-dom";
import {Search,Sun,Moon,Monitor,ArrowUpRight,Check,FileText,Expand} from "lucide-react";
import {list,rpc,errorText,remove} from "../services/data";
import {configured} from "../services/client";
import {useData,useDebounce} from "../hooks/useData";
import {Button,Modal,State,FileLink} from "./UI";
import {date,type Row} from "../config/types";
export const categories:Record<string,string>={application:"Заявки",appeal:"Звернення",system:"Системні",city:"Міські",important:"Важливі",emergency:"Термінові",news:"Новини",service:"Послуги"};
export function ThemeControl(){const [value,setValue]=useState(()=>localStorage.getItem("portal-theme")||"system");useEffect(()=>{const fn=(e:Event)=>setValue((e as CustomEvent<string>).detail);window.addEventListener("portal-theme-change",fn);return()=>window.removeEventListener("portal-theme-change",fn)},[]);useEffect(()=>{const m=matchMedia("(prefers-color-scheme: dark)");const apply=()=>{document.documentElement.dataset.theme=value==="system"?(m.matches?"dark":"light"):value;localStorage.setItem("portal-theme",value)};apply();m.addEventListener("change",apply);return()=>m.removeEventListener("change",apply)},[value]);return <label className="theme-control"><span className="sr-only">Тема</span>{value==="dark"?<Moon size={18}/>:value==="light"?<Sun size={18}/>:<Monitor size={18}/>}<select aria-label="Тема оформлення" value={value} onChange={e=>{setValue(e.target.value);window.dispatchEvent(new CustomEvent("portal-theme-change",{detail:e.target.value}))}}><option value="system">Системна</option><option value="light">Світла</option><option value="dark">Темна</option></select></label>}
type Result={title:string;url:string;group:string};
export async function suggestions(query:string):Promise<Result[]>{if(!query.trim())return [];const groups=[["services","Послуги"],["documents","Документи"],["news","Новини"],["faqs","FAQ"]];const rows=await Promise.all(groups.map(async([table,group])=>{const r=await list(table,{search:query,searchColumns:table==="faqs"?["question","answer"]:["title"],...(table!=="faqs"?{visible:true}:{}),size:5});return r.rows.map(v=>({title:v.title||v.question,url:table==="faqs"?"/help":"/"+table+"/"+v.slug,group}))}));return rows.flat()}
export function SearchSuggestions({query}:{query:string}){const d=useDebounce(query),q=useData(()=>suggestions(d),[d]);if(!d.trim())return null;return <div className="search-suggestions"><State loading={q.loading} error={q.error}>{q.data?.map((r,i)=><Link key={i} to={r.url}><small>{r.group}</small>{r.title}<ArrowUpRight size={16}/></Link>)}{!q.data?.length&&<small>Нічого не знайдено. Спробуйте інший запит.</small>}</State></div>}
export function CommandPalette({shortcut=true}:{shortcut?:boolean}){const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[index,setIndex]=useState(0);const navigate=useNavigate(),loc=useLocation();const d=useDebounce(query);const q=useData(async()=>d.trim()?suggestions(d):[...JSON.parse(localStorage.getItem("portal-recent")||"[]").slice(0,4).map((url:string)=>({title:url,url,group:"Останні сторінки"})),...[{title:"Послуги",url:"/services"},{title:"Черкаси зараз",url:"/now"},{title:"Мій кабінет",url:"/account"},{title:"Мої документи",url:"/account/documents"}].map(v=>({...v,group:"Швидкий перехід"})),...(await list("services",{eq:{featured:true},visible:true,size:4})).rows.map(v=>({title:v.title,url:"/services/"+v.slug,group:"Популярні послуги"}))],[d]);useEffect(()=>{let old:string[]=[];try{old=JSON.parse(localStorage.getItem("portal-recent")||"[]")}catch{}localStorage.setItem("portal-recent",JSON.stringify([loc.pathname,...old.filter(p=>p!==loc.pathname)].slice(0,8)));setOpen(false)},[loc.pathname]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(shortcut&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setOpen(v=>!v)}};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)},[]);useEffect(()=>setIndex(0),[d]);return <><button className="icon-button command-trigger" aria-label="Пошук — Ctrl+K" onClick={()=>setOpen(true)}><Search size={20}/><kbd>⌘ K</kbd></button>{open&&<Modal title="Пошук та швидкий перехід" onClose={()=>setOpen(false)}><div className="command-panel" onKeyDown={e=>{const rows=q.data||[];if(e.key==="ArrowDown"){e.preventDefault();setIndex(v=>Math.min(v+1,rows.length-1))}if(e.key==="ArrowUp"){e.preventDefault();setIndex(v=>Math.max(v-1,0))}if(e.key==="Enter"&&rows[index]){e.preventDefault();navigate(rows[index].url);setOpen(false)}}}><input autoFocus type="search" placeholder="Послуги, документи, новини…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Пошуковий запит" aria-activedescendant={"command-"+index}/><State loading={q.loading} error={q.error}><div role="listbox">{q.data?.map((r,i)=><Link id={"command-"+i} role="option" aria-selected={i===index} className={i===index?"selected":""} key={i} to={r.url}><small>{r.group}</small><span>{r.title}</span><ArrowUpRight size={18}/></Link>)}</div></State><small>↑ ↓ Вибрати · Enter Відкрити · Esc Закрити</small></div></Modal>}</>}
export const priorities:Record<string,string>={low:"Низький",normal:"Звичайний",high:"Високий",urgent:"Терміновий"};
export function Deadline({value}:{value?:string}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(t)},[]);if(!value)return null;const diff=Date.parse(value)-now;return <span className={"deadline "+(diff<0?"overdue":diff<172800000?"near":"")}>{diff<0?"Термін минув":diff<86400000?"Менше доби до терміну":"До завершення: "+Math.ceil(diff/86400000)+" дн."} · {date(value)}</span>}
export function ApplicationProgress({status}:{status:string}){const steps=["submitted","received","in_review","approved","completed"],index=status==="needs_more_info"?2:steps.indexOf(status);return <ol className="application-progress" aria-label="Етапи заяви">{["Подано","Отримано","На розгляді","Рішення","Завершено"].map((v,i)=><li key={v} className={i<index?"done":i===index?"current":""}><span>{i<index?<Check size={16}/>:i+1}</span>{v}</li>)}{["rejected","cancelled"].includes(status)&&<li className="overdue">{status==="rejected"?"Відхилено":"Скасовано"}</li>}</ol>}
export function DocumentPicker({application,field,kind,onChange}:{application:string;field:string;kind:string;onChange:()=>void}){const [open,setOpen]=useState(false),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const d=useDebounce(search);const q=useData(()=>open?list("user_documents",{search:d,searchColumns:["name"],size:100}):Promise.resolve({rows:[],count:0}),[open,d]);return <><Button type="button" className="secondary" onClick={()=>setOpen(true)}>Вибрати з моїх документів</Button>{open&&<Modal title="Мої документи" onClose={()=>setOpen(false)}><input type="search" placeholder="Пошук за назвою" value={search} onChange={e=>setSearch(e.target.value)}/><State loading={q.loading} error={q.error}>{q.data?.rows.filter(v=>kind==="pdf"?v.mime_type==="application/pdf":kind==="image"?v.mime_type?.startsWith("image/"):true).map(v=><div className="list-item row" key={v.id}><div><FileText size={18}/> {v.name}<small>{date(v.created_at)} · {Math.ceil(v.size_bytes/1024)} КБ</small></div><Button busy={busy} onClick={async()=>{setBusy(true);setError("");try{await rpc("link_application_document",{p_application:application,p_document:v.id,p_field:field});onChange();setOpen(false)}catch(e){setError(errorText(e))}finally{setBusy(false)}}}>Вибрати</Button></div>)}</State>{error&&<p className="field-error">{error}</p>}</Modal>}</>}
export function LinkedDocuments({application,onChange,editable=false}:{application:string;onChange?:()=>void;editable?:boolean}){const q=useData(()=>rpc("application_linked_documents",{p_id:application}),[application]);return <>{q.error&&<p className="field-error">{q.error}</p>}{q.data?.map((v:Row)=><div key={v.id} className="list-item row"><FileLink bucket="service-documents" path={v.path} name={v.name}/>{editable&&<Button className="secondary small" onClick={async()=>{try{await remove("application_document_links",v.id);q.reload();onChange?.()}catch(e){alert(errorText(e))}}}>Прибрати</Button>}</div>)}</>}
export function PDFViewer({url,title}:{url:string;title:string}){const [page,setPage]=useState(1),[zoom,setZoom]=useState(100);const ref=useRef<HTMLDivElement>(null);return <div className="pdf-module" ref={ref}><div className="pdf-toolbar"><label>Сторінка<input aria-label="Сторінка PDF" type="number" min={1} value={page} onChange={e=>setPage(Math.max(1,Number(e.target.value)||1))}/></label><label>Масштаб<select aria-label="Масштаб PDF" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[75,100,125,150,200].map(v=><option key={v}>{v}</option>)}</select></label><Button className="secondary" onClick={()=>void ref.current?.requestFullscreen()}><Expand size={18}/> На весь екран</Button><a href={url} target="_blank" rel="noreferrer">Відкрити окремо ↗</a></div><iframe className="pdf-viewer" src={url+"#page="+page+"&zoom="+zoom} title={title}/></div>}
